channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - pip
  - jupyterlab
  - nb_conda
  - jupyterlab-git
  - pytest
  - psycopg2
  - scikit-learn
  - html5lib
  - pip:
    - dagster==1.3.0
    #- dagster-docker==0.19.0
    #- dagster-ssh==0.19.0
    - dagster-pandas==0.19.0
    - dagster-postgres==0.19.0
    - dagster-dbt==0.19.0
    #- dagster_slack==0.19.0
    #- dagster_aws==0.19.0
    #- dagster-pyspark==0.19.0
    #- dagster-shell==0.19.0
    - dagster_duckdb==0.19.0
    - dagster_duckdb_pandas==0.19.0
    - dagster-cloud==1.3.0
    - dagstermill==0.19.0
    - dagit==1.3.0
    - dbt-postgres==1.4.3
    - dbt-duckdb
    - boto3
    - responses
    - plotnine
    - requests
